### ISSUE TITLE
macOS Catalina example_controller fails to load dyld

### ISSUE THREAD

**Issue by zmk5** [cyberbotics/webots_ros2#119]
**Describe the Bug**
When attempting to test the `webots_ros2` package, I get an error saying that my `WEBOTS_HOME` was not set correctly, but the real issue is that `_controller.so` file for python 3.8 cannot be found. Webots will start up but the ROS2 controller will fail.

**Steps to Reproduce**
1. Set the following:
```bash
~$ export WEBOTS_HOME=/Applications/Webots.app
~$ export PYTHONPATH=$PYTHONPATH:${WEBOTS_HOME}/lib/controller/python38
~$ export DYLD_LIBRARY_PATH=${WEBOTS_HOME}/lib/controller:$DYLD_LIBRARY_PATH
```
2. Install `webots_ros2`
3. Attempt to run the example controller: `ros2 launch webots_ros2_examples example.launch.py`

**Expected behavior**
Webots should open along with the functioning ROS2 controller.

**Affected Packages**
List of affected packages:
  - webots_ros2_A
  - webots_ros2_B

**Screenshots**

```bash
zmk5-MBP:webots_ws zmk5$ ros2 launch webots_ros2_examples example.launch.py
[INFO] [launch]: All log files can be found below /Users/zmk5/.ros/log/2020-08-04-17-22-12-071529-zmk5-MBP-22355
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [webots_launcher-1]: process started with pid [22367]
[INFO] [example_controller-2]: process started with pid [22368]
[example_controller-2] "WEBOTS_HOME" is not correctly set.Traceback (most recent call last):
[example_controller-2]   File "/Users/zmk5/ROS2/webots_ws/install/webots_ros2_examples/lib/webots_ros2_examples/example_controller", line 33, in <module>
[example_controller-2]     sys.exit(load_entry_point('webots-ros2-examples', 'console_scripts', 'example_controller')())
[example_controller-2]   File "/Users/zmk5/ROS2/webots_ws/install/webots_ros2_examples/lib/webots_ros2_examples/example_controller", line 25, in importlib_load_entry_point
[example_controller-2]     return next(matches).load()
[example_controller-2]   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
[example_controller-2]     module = import_module(match.group('module'))
[example_controller-2]   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
[example_controller-2]     return _bootstrap._gcd_import(name[level:], package, level)
[example_controller-2]   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[example_controller-2]   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[example_controller-2]   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[example_controller-2]   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[example_controller-2]   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
[example_controller-2]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[example_controller-2]   File "/Users/zmk5/ROS2/webots_ws/build/webots_ros2_examples/webots_ros2_examples/example_controller.py", line 17, in <module>
[example_controller-2]     from webots_ros2_core.webots_node import WebotsNode
[example_controller-2]   File "/Users/zmk5/ROS2/webots_ws/build/webots_ros2_core/webots_ros2_core/webots_node.py", line 39, in <module>
[example_controller-2]     raise e
[example_controller-2]   File "/Users/zmk5/ROS2/webots_ws/build/webots_ros2_core/webots_ros2_core/webots_node.py", line 35, in <module>
[example_controller-2]     from controller import Supervisor
[example_controller-2]   File "/Applications/Webots.app/lib/controller/python38/controller.py", line 31, in <module>
[example_controller-2]     import _controller
[example_controller-2] ImportError: dlopen(/Applications/Webots.app/lib/controller/python38/_controller.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.8/Python
[example_controller-2]   Referenced from: /Applications/Webots.app/lib/controller/python38/_controller.so
[example_controller-2]   Reason: image not found
[ERROR] [example_controller-2]: process has died [pid 22368, exit code 1, cmd '/Users/zmk5/ROS2/webots_ws/install/webots_ros2_examples/lib/webots_ros2_examples/example_controller --ros-args --params-file /var/folders/wq/bwd_8njd6lz3ggtfzt6k_5cc0000gn/T/launch_params__453um_9'].
[webots_launcher-1] AL lib: (WW) UpdateDeviceParams: SSE performs best with multiple of 4 update sizes (1114)
[INFO] [webots_launcher-1]: process has finished cleanly [pid 22367]
```

**System**
 - Webots Version: R2020b
 - ROS Version: Foxy
 - Operating System: macOS Catalina
 - Graphics Card: Radeon Pro 560X and Intel UHD Graphics 630

**Additional context**
After playing around with it a bit, I think the system is attempting to load the dyld from `/Library/Frameworks/Python.framework/Versions/3.8/Python`. However, this does not exist since I use the homebrew version of Python 3.

**Comment by DavidMansolino** [comment]
Unfortunately, Webots is not compatible out of the box with Python 3 from homebrew, we have plan to improve this (#2066), but in the meantime, it is recommended to use the python version from: https://www.python.org/downloads/
