### ISSUE TITLE
[ERROR] [driver.EXE-2]: process has die,dexit code 3221226505

### ISSUE THREAD

**Issue by wangruoyao** [cyberbotics/webots_ros2#440]
C:\ros2_ws\my_package>ros2 launch my_package robot_launch.py
[INFO] [launch]: All log files can be found below C:\Users\.ros\log\2022-05-07-20-22-10-741454-294896
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [webots-1]: process started with pid [294292]
[INFO] [driver.EXE-2]: process started with pid [294200]
[ERROR] [driver.EXE-2]: process has died [pid 294200, exit code 3221226505, cmd 'C:\ros2_ws\install\webots_ros2_driver\lib\webots_ros2_driver\driver.EXE --ros-args --params-file C:\Users\AppData\Local\Temp\launch_params_jybqzfog'].

simply follow the steps here https://docs.ros.org/en/galactic/Tutorials/Simulators/Webots/Setting-up-a-Robot-Simulation-Webots.html

[driver.EXE-2]

 - Webots Version: R2022a 
 - ROS Version: foxy
 - Operating System: windows10
 - Graphics Card: GTX1070Ti

Don't know why it happened.
Before that, as the tutorial said I use colon to build, CMake was installed and created system environment already, it cannot find. Then I installed another CMake in VS2019. And built it successfully.

When I start a new command and call install\local_setup.bat, then input C:\ros2_ws>ros2 topic pub /cmd_vel geometry_msgs/Twist  "linear: { x: 0.1 }"
The command shows: Failed to initialize init_options: failed to load shared library 'C:\dev\ros2_foxy\bin/rmw_fastrtps_cpp.dll' due to LoadLibrary error: 126, at C:\ci\ws\src\ros2\rcutils\src\shared_library.c:88, at C:\ci\ws\src\ros2\rmw_implementation\rmw_implementation\src\functions.cpp:84, at C:\ci\ws\src\ros2\rcl\rcl\src\rcl\init_options.c:61

**Comment by wangruoyao** [comment]
I also trid https://github.com/cyberbotics/webots_ros2/wiki/Getting-Started  

C:\ros2_ws>ros2 launch webots_ros2_universal_robot multirobot_launch.py
[INFO] [launch]: All log files can be found below C:\Users\wangry\.ros\log\2022-05-07-21-55-05-245261-wangry-303616
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [webots-1]: process started with pid [304664]
[INFO] [abb_controller.EXE-2]: process started with pid [303896]
[INFO] [ur5e_controller.EXE-3]: process started with pid [244224]
[INFO] [driver.EXE-4]: process started with pid [303648]
[INFO] [driver.EXE-5]: process started with pid [281632]
[INFO] [spawner.py-6]: process started with pid [304780]
[INFO] [spawner.py-7]: process started with pid [301408]
[INFO] [spawner.py-8]: process started with pid [304116]
[INFO] [spawner.py-9]: process started with pid [300456]
[spawner.py-7] Traceback (most recent call last):
[spawner.py-7]   File "C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py", line 204, in <module>
[spawner.py-7]     sys.exit(main())
[spawner.py-7]   File "C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py", line 75, in main
[spawner.py-7]     rclpy.init(args=args)
[spawner.py-7]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\__init__.py", line 71, in init
[spawner.py-7]     return context.init(args)
[spawner.py-7]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\context.py", line 59, in init
[spawner.py-7]     rclpy_implementation.rclpy_init(args if args is not None else sys.argv, capsule)
[spawner.py-7] RuntimeError: Failed to initialize init_options: failed to load shared library 'C:\dev\ros2_foxy\bin/rmw_fastrtps_cpp.dll' due to LoadLibrary error: 126, at C:\ci\ws\src\ros2\rcutils\src\shared_library.c:88, at C:\ci\ws\src\ros2\rmw_implementation\rmw_implementation\src\functions.cpp:84, at C:\ci\ws\src\ros2\rcl\rcl\src\rcl\init_options.c:61
[spawner.py-9] Traceback (most recent call last):
[spawner.py-9]   File "C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py", line 204, in <module>
[spawner.py-9]     sys.exit(main())
[spawner.py-9]   File "C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py", line 75, in main
[spawner.py-9]     rclpy.init(args=args)
[spawner.py-9]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\__init__.py", line 71, in init
[spawner.py-9]     return context.init(args)
[spawner.py-9]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\context.py", line 59, in init
[spawner.py-9]     rclpy_implementation.rclpy_init(args if args is not None else sys.argv, capsule)
[spawner.py-9] RuntimeError: Failed to initialize init_options: failed to load shared library 'C:\dev\ros2_foxy\bin/rmw_fastrtps_cpp.dll' due to LoadLibrary error: 126, at C:\ci\ws\src\ros2\rcutils\src\shared_library.c:88, at C:\ci\ws\src\ros2\rmw_implementation\rmw_implementation\src\functions.cpp:84, at C:\ci\ws\src\ros2\rcl\rcl\src\rcl\init_options.c:61
[spawner.py-6] Traceback (most recent call last):
[spawner.py-6]   File "C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py", line 204, in <module>
[spawner.py-6]     sys.exit(main())
[spawner.py-6]   File "C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py", line 75, in main
[spawner.py-6]     rclpy.init(args=args)
[spawner.py-6]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\__init__.py", line 71, in init
[spawner.py-6]     return context.init(args)
[spawner.py-6]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\context.py", line 59, in init
[spawner.py-6]     rclpy_implementation.rclpy_init(args if args is not None else sys.argv, capsule)
[spawner.py-6] RuntimeError: Failed to initialize init_options: failed to load shared library 'C:\dev\ros2_foxy\bin/rmw_fastrtps_cpp.dll' due to LoadLibrary error: 126, at C:\ci\ws\src\ros2\rcutils\src\shared_library.c:88, at C:\ci\ws\src\ros2\rmw_implementation\rmw_implementation\src\functions.cpp:84, at C:\ci\ws\src\ros2\rcl\rcl\src\rcl\init_options.c:61
[spawner.py-8] Traceback (most recent call last):
[spawner.py-8]   File "C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py", line 204, in <module>
[spawner.py-8]     sys.exit(main())
[spawner.py-8]   File "C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py", line 75, in main
[spawner.py-8]     rclpy.init(args=args)
[spawner.py-8]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\__init__.py", line 71, in init
[spawner.py-8]     return context.init(args)
[spawner.py-8]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\context.py", line 59, in init
[spawner.py-8]     rclpy_implementation.rclpy_init(args if args is not None else sys.argv, capsule)
[spawner.py-8] RuntimeError: Failed to initialize init_options: failed to load shared library 'C:\dev\ros2_foxy\bin/rmw_fastrtps_cpp.dll' due to LoadLibrary error: 126, at C:\ci\ws\src\ros2\rcutils\src\shared_library.c:88, at C:\ci\ws\src\ros2\rmw_implementation\rmw_implementation\src\functions.cpp:84, at C:\ci\ws\src\ros2\rcl\rcl\src\rcl\init_options.c:61
[ERROR] [spawner.py-7]: process has died [pid 301408, exit code 1, cmd 'python.exe C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py ur_joint_state_broadcaster -c ur5e/controller_manager --controller-manager-timeout 75 --ros-args'].
[ERROR] [spawner.py-6]: process has died [pid 304780, exit code 1, cmd 'python.exe C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py ur_joint_trajectory_controller -c ur5e/controller_manager --controller-manager-timeout 75 --ros-args'].
[ERROR] [spawner.py-9]: process has died [pid 300456, exit code 1, cmd 'python.exe C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py abb_joint_state_broadcaster -c abb/controller_manager --controller-manager-timeout 75 --ros-args'].
[ERROR] [spawner.py-8]: process has died [pid 304116, exit code 1, cmd 'python.exe C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py abb_joint_trajectory_controller -c abb/controller_manager --controller-manager-timeout 75 --ros-args'].
[abb_controller.EXE-2] Traceback (most recent call last):
[abb_controller.EXE-2]   File "C:\ros2_ws\install\webots_ros2_universal_robot\lib\webots_ros2_universal_robot\abb_controller-script.py", line 33, in <module>
[abb_controller.EXE-2]     sys.exit(load_entry_point('webots-ros2-universal-robot==1.2.2', 'console_scripts', 'abb_controller')())
[abb_controller.EXE-2]   File "C:\ros2_ws\install\webots_ros2_universal_robot\Lib\site-packages\webots_ros2_universal_robot\abb_controller.py", line 73, in main
[abb_controller.EXE-2]     rclpy.init(args=args)
[abb_controller.EXE-2]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\__init__.py", line 71, in init
[abb_controller.EXE-2]     return context.init(args)
[abb_controller.EXE-2]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\context.py", line 59, in init
[abb_controller.EXE-2]     rclpy_implementation.rclpy_init(args if args is not None else sys.argv, capsule)
[abb_controller.EXE-2] RuntimeError: Failed to initialize init_options: failed to load shared library 'C:\dev\ros2_foxy\bin/rmw_fastrtps_cpp.dll' due to LoadLibrary error: 126, at C:\ci\ws\src\ros2\rcutils\src\shared_library.c:88, at C:\ci\ws\src\ros2\rmw_implementation\rmw_implementation\src\functions.cpp:84, at C:\ci\ws\src\ros2\rcl\rcl\src\rcl\init_options.c:61
[ur5e_controller.EXE-3] Traceback (most recent call last):
[ur5e_controller.EXE-3]   File "C:\ros2_ws\install\webots_ros2_universal_robot\lib\webots_ros2_universal_robot\ur5e_controller-script.py", line 33, in <module>
[ur5e_controller.EXE-3]     sys.exit(load_entry_point('webots-ros2-universal-robot==1.2.2', 'console_scripts', 'ur5e_controller')())
[ur5e_controller.EXE-3]   File "C:\ros2_ws\install\webots_ros2_universal_robot\Lib\site-packages\webots_ros2_universal_robot\ur5e_controller.py", line 69, in main
[ur5e_controller.EXE-3]     rclpy.init(args=args)
[ur5e_controller.EXE-3]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\__init__.py", line 71, in init
[ur5e_controller.EXE-3]     return context.init(args)
[ur5e_controller.EXE-3]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\context.py", line 59, in init
[ur5e_controller.EXE-3]     rclpy_implementation.rclpy_init(args if args is not None else sys.argv, capsule)
[ur5e_controller.EXE-3] RuntimeError: Failed to initialize init_options: failed to load shared library 'C:\dev\ros2_foxy\bin/rmw_fastrtps_cpp.dll' due to LoadLibrary error: 126, at C:\ci\ws\src\ros2\rcutils\src\shared_library.c:88, at C:\ci\ws\src\ros2\rmw_implementation\rmw_implementation\src\functions.cpp:84, at C:\ci\ws\src\ros2\rcl\rcl\src\rcl\init_options.c:61
[ERROR] [abb_controller.EXE-2]: process has died [pid 303896, exit code 1, cmd 'C:\ros2_ws\install\webots_ros2_universal_robot\lib\webots_ros2_universal_robot\abb_controller.EXE --ros-args -r __ns:=/abb'].
[ERROR] [ur5e_controller.EXE-3]: process has died [pid 244224, exit code 1, cmd 'C:\ros2_ws\install\webots_ros2_universal_robot\lib\webots_ros2_universal_robot\ur5e_controller.EXE --ros-args -r __ns:=/ur5e'].
[ERROR] [driver.EXE-5]: process has died [pid 281632, exit code 3221226505, cmd 'C:\ros2_ws\install\webots_ros2_driver\lib\webots_ros2_driver\driver.EXE --ros-args -r __ns:=/abb --params-file C:\Users\AppData\Local\Temp\launch_params_5o8n_l8u --params-file C:\Users\AppData\Local\Temp\launch_params_b8x7j13_ --params-file C:\ros2_ws\install\webots_ros2_universal_robot\share\webots_ros2_universal_robot\resource\ros2_control_abb_config.yaml'].
[ERROR] [driver.EXE-4]: process has died [pid 303648, exit code 3221226505, cmd 'C:\ros2_ws\install\webots_ros2_driver\lib\webots_ros2_driver\driver.EXE --ros-args -r __ns:=/ur5e --params-file C:\Users\AppData\Local\Temp\launch_params_fo4ih085 --params-file C:\Users\AppData\Local\Temp\launch_params_r9m0sl5i --params-file C:\ros2_ws\install\webots_ros2_universal_robot\share\webots_ros2_universal_robot\resource\ros2_control_config.yaml'].
[INFO] [webots-1]: process has finished cleanly [pid 304664]

C:\ros2_ws>ros2 launch webots_ros2_universal_robot multirobot_launch.py
[INFO] [launch]: All log files can be found below C:\Users\.ros\log\2022-05-07-21-55-53-456522--290064
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [webots-1]: process started with pid [304332]
[INFO] [abb_controller.EXE-2]: process started with pid [304920]
[INFO] [ur5e_controller.EXE-3]: process started with pid [304980]
[INFO] [driver.EXE-4]: process started with pid [304192]
[INFO] [driver.EXE-5]: process started with pid [303160]
[INFO] [spawner.py-6]: process started with pid [303192]
[INFO] [spawner.py-7]: process started with pid [304996]
[INFO] [spawner.py-8]: process started with pid [294788]
[INFO] [spawner.py-9]: process started with pid [302412]
[spawner.py-6] Traceback (most recent call last):
[spawner.py-6]   File "C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py", line 204, in <module>
[spawner.py-6]     sys.exit(main())
[spawner.py-6]   File "C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py", line 75, in main
[spawner.py-6]     rclpy.init(args=args)
[spawner.py-6]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\__init__.py", line 71, in init
[spawner.py-6]     return context.init(args)
[spawner.py-6]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\context.py", line 59, in init
[spawner.py-6]     rclpy_implementation.rclpy_init(args if args is not None else sys.argv, capsule)
[spawner.py-6] RuntimeError: Failed to initialize init_options: failed to load shared library 'C:\dev\ros2_foxy\bin/rmw_fastrtps_cpp.dll' due to LoadLibrary error: 126, at C:\ci\ws\src\ros2\rcutils\src\shared_library.c:88, at C:\ci\ws\src\ros2\rmw_implementation\rmw_implementation\src\functions.cpp:84, at C:\ci\ws\src\ros2\rcl\rcl\src\rcl\init_options.c:61
[spawner.py-8] Traceback (most recent call last):
[spawner.py-8]   File "C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py", line 204, in <module>
[spawner.py-8]     sys.exit(main())
[spawner.py-8]   File "C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py", line 75, in main
[spawner.py-8]     rclpy.init(args=args)
[spawner.py-8]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\__init__.py", line 71, in init
[spawner.py-8]     return context.init(args)
[spawner.py-8]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\context.py", line 59, in init
[spawner.py-8]     rclpy_implementation.rclpy_init(args if args is not None else sys.argv, capsule)
[spawner.py-8] RuntimeError: Failed to initialize init_options: failed to load shared library 'C:\dev\ros2_foxy\bin/rmw_fastrtps_cpp.dll' due to LoadLibrary error: 126, at C:\ci\ws\src\ros2\rcutils\src\shared_library.c:88, at C:\ci\ws\src\ros2\rmw_implementation\rmw_implementation\src\functions.cpp:84, at C:\ci\ws\src\ros2\rcl\rcl\src\rcl\init_options.c:61
[spawner.py-7] Traceback (most recent call last):
[spawner.py-7]   File "C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py", line 204, in <module>
[spawner.py-7]     sys.exit(main())
[spawner.py-7]   File "C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py", line 75, in main
[spawner.py-7]     rclpy.init(args=args)
[spawner.py-7]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\__init__.py", line 71, in init
[spawner.py-7]     return context.init(args)
[spawner.py-7]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\context.py", line 59, in init
[spawner.py-7]     rclpy_implementation.rclpy_init(args if args is not None else sys.argv, capsule)
[spawner.py-7] RuntimeError: Failed to initialize init_options: failed to load shared library 'C:\dev\ros2_foxy\bin/rmw_fastrtps_cpp.dll' due to LoadLibrary error: 126, at C:\ci\ws\src\ros2\rcutils\src\shared_library.c:88, at C:\ci\ws\src\ros2\rmw_implementation\rmw_implementation\src\functions.cpp:84, at C:\ci\ws\src\ros2\rcl\rcl\src\rcl\init_options.c:61
[spawner.py-9] Traceback (most recent call last):
[spawner.py-9]   File "C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py", line 204, in <module>
[spawner.py-9]     sys.exit(main())
[spawner.py-9]   File "C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py", line 75, in main
[spawner.py-9]     rclpy.init(args=args)
[spawner.py-9]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\__init__.py", line 71, in init
[spawner.py-9]     return context.init(args)
[spawner.py-9]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\context.py", line 59, in init
[spawner.py-9]     rclpy_implementation.rclpy_init(args if args is not None else sys.argv, capsule)
[spawner.py-9] RuntimeError: Failed to initialize init_options: failed to load shared library 'C:\dev\ros2_foxy\bin/rmw_fastrtps_cpp.dll' due to LoadLibrary error: 126, at C:\ci\ws\src\ros2\rcutils\src\shared_library.c:88, at C:\ci\ws\src\ros2\rmw_implementation\rmw_implementation\src\functions.cpp:84, at C:\ci\ws\src\ros2\rcl\rcl\src\rcl\init_options.c:61
[ERROR] [spawner.py-6]: process has died [pid 303192, exit code 1, cmd 'python.exe C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py ur_joint_trajectory_controller -c ur5e/controller_manager --controller-manager-timeout 75 --ros-args'].
[ERROR] [spawner.py-8]: process has died [pid 294788, exit code 1, cmd 'python.exe C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py abb_joint_trajectory_controller -c abb/controller_manager --controller-manager-timeout 75 --ros-args'].
[ERROR] [spawner.py-9]: process has died [pid 302412, exit code 1, cmd 'python.exe C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py abb_joint_state_broadcaster -c abb/controller_manager --controller-manager-timeout 75 --ros-args'].
[ERROR] [spawner.py-7]: process has died [pid 304996, exit code 1, cmd 'python.exe C:\ros2_ws\install\controller_manager\lib\controller_manager\spawner.py ur_joint_state_broadcaster -c ur5e/controller_manager --controller-manager-timeout 75 --ros-args'].
[abb_controller.EXE-2] Traceback (most recent call last):
[abb_controller.EXE-2]   File "C:\ros2_ws\install\webots_ros2_universal_robot\lib\webots_ros2_universal_robot\abb_controller-script.py", line 33, in <module>
[abb_controller.EXE-2]     sys.exit(load_entry_point('webots-ros2-universal-robot==1.2.2', 'console_scripts', 'abb_controller')())
[abb_controller.EXE-2]   File "C:\ros2_ws\install\webots_ros2_universal_robot\Lib\site-packages\webots_ros2_universal_robot\abb_controller.py", line 73, in main
[abb_controller.EXE-2]     rclpy.init(args=args)
[abb_controller.EXE-2]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\__init__.py", line 71, in init
[abb_controller.EXE-2]     return context.init(args)
[abb_controller.EXE-2]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\context.py", line 59, in init
[abb_controller.EXE-2]     rclpy_implementation.rclpy_init(args if args is not None else sys.argv, capsule)
[abb_controller.EXE-2] RuntimeError: Failed to initialize init_options: failed to load shared library 'C:\dev\ros2_foxy\bin/rmw_fastrtps_cpp.dll' due to LoadLibrary error: 126, at C:\ci\ws\src\ros2\rcutils\src\shared_library.c:88, at C:\ci\ws\src\ros2\rmw_implementation\rmw_implementation\src\functions.cpp:84, at C:\ci\ws\src\ros2\rcl\rcl\src\rcl\init_options.c:61
[ur5e_controller.EXE-3] Traceback (most recent call last):
[ur5e_controller.EXE-3]   File "C:\ros2_ws\install\webots_ros2_universal_robot\lib\webots_ros2_universal_robot\ur5e_controller-script.py", line 33, in <module>
[ur5e_controller.EXE-3]     sys.exit(load_entry_point('webots-ros2-universal-robot==1.2.2', 'console_scripts', 'ur5e_controller')())
[ur5e_controller.EXE-3]   File "C:\ros2_ws\install\webots_ros2_universal_robot\Lib\site-packages\webots_ros2_universal_robot\ur5e_controller.py", line 69, in main
[ur5e_controller.EXE-3]     rclpy.init(args=args)
[ur5e_controller.EXE-3]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\__init__.py", line 71, in init
[ur5e_controller.EXE-3]     return context.init(args)
[ur5e_controller.EXE-3]   File "C:\dev\ros2_foxy\Lib\site-packages\rclpy\context.py", line 59, in init
[ur5e_controller.EXE-3]     rclpy_implementation.rclpy_init(args if args is not None else sys.argv, capsule)
[ur5e_controller.EXE-3] RuntimeError: Failed to initialize init_options: failed to load shared library 'C:\dev\ros2_foxy\bin/rmw_fastrtps_cpp.dll' due to LoadLibrary error: 126, at C:\ci\ws\src\ros2\rcutils\src\shared_library.c:88, at C:\ci\ws\src\ros2\rmw_implementation\rmw_implementation\src\functions.cpp:84, at C:\ci\ws\src\ros2\rcl\rcl\src\rcl\init_options.c:61
[ERROR] [abb_controller.EXE-2]: process has died [pid 304920, exit code 1, cmd 'C:\ros2_ws\install\webots_ros2_universal_robot\lib\webots_ros2_universal_robot\abb_controller.EXE --ros-args -r __ns:=/abb'].
[ERROR] [ur5e_controller.EXE-3]: process has died [pid 304980, exit code 1, cmd 'C:\ros2_ws\install\webots_ros2_universal_robot\lib\webots_ros2_universal_robot\ur5e_controller.EXE --ros-args -r __ns:=/ur5e'].
[ERROR] [driver.EXE-4]: process has died [pid 304192, exit code 3221226505, cmd 'C:\ros2_ws\install\webots_ros2_driver\lib\webots_ros2_driver\driver.EXE --ros-args -r __ns:=/ur5e --params-file C:\Users\AppData\Local\Temp\launch_params_q2dwldsw --params-file C:\Users\AppData\Local\Temp\launch_params_rp6d7fqk --params-file C:\ros2_ws\install\webots_ros2_universal_robot\share\webots_ros2_universal_robot\resource\ros2_control_config.yaml'].
[ERROR] [driver.EXE-5]: process has died [pid 303160, exit code 3221226505, cmd 'C:\ros2_ws\install\webots_ros2_driver\lib\webots_ros2_driver\driver.EXE --ros-args -r __ns:=/abb --params-file C:\Users\AppData\Local\Temp\launch_params_ty7ys6ct --params-file C:\Users\AppData\Local\Temp\launch_params_yg3sp71l --params-file C:\ros2_ws\install\webots_ros2_universal_robot\share\webots_ros2_universal_robot\resource\ros2_control_abb_config.yaml'].
