### ISSUE TITLE
ros2_supervisor crashing!

### ISSUE THREAD

**Issue by prasuchit** [cyberbotics/webots_ros2#462]
Hi,

I'm completely new to webots and so far, the instructions have been very clear and it was very easy to setup and get it working. I was able to quickly test out the ur5e example as well, but then I ran into a problem. After one successful plan execution I was seeing the error "Detected jump back in time of ABCDs. Clearing TF buffer." on an infinite loop and it can't plan/execute anything after that. 

So I wanted to test it out with my own URDF by following [these](https://github.com/cyberbotics/webots_ros2/wiki/Tutorial-Ros2Supervisor-Import-your-Urdf-Robot) instructions and ended up with the following error:

[driver-6] Cannot open file: /tmp/webots-20224-lzL6L4/WEBOTS_SERVER (retry count 1)
[robot_state_publisher-5] [INFO] [1661648572.341137393] [robot_state_publisher]: got segment 
[webots-3] Warning: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-ros'
[ros2_supervisor.py-4] Traceback (most recent call last):
[ros2_supervisor.py-4]   File "/home/ros/workspaces/simulator_ws/install/webots_ros2_driver/lib/webots_ros2_driver/ros2_supervisor.py", line 31, in <module>
[ros2_supervisor.py-4]     from urdf2webots.importer import convertUrdfFile, convertUrdfContent
[ros2_supervisor.py-4] ModuleNotFoundError: No module named 'urdf2webots'
[ERROR] [ros2_supervisor.py-4]: process has died [pid 20226, exit code 1, cmd '/home/ros/workspaces/simulator_ws/install/webots_ros2_driver/lib/webots_ros2_driver/ros2_supervisor.py --ros-args'].
[INFO] [ros2_supervisor.py-4]: process started with pid [20274]

This keeps printing on a loop and then the process dies. Kindly help. Thanks.

**Comment by prasuchit** [comment]
@omichel @DavidMansolino @stefaniapedrazzi Kindly help, I'm on a deadline to get this working. Thanks.

**Comment by lukicdarkoo** [comment]
The issue is hidden behind this log message:
```
[ros2_supervisor.py-4] ModuleNotFoundError: No module named 'urdf2webots'
```

Is there a chance you forgot the `--recurse-submodules` flag when cloning?
https://github.com/cyberbotics/webots_ros2/wiki/Build-and-Install#linux
or can you make sure the package is installed:
```
sudo apt install ros-${ROS_DISTRO}-webots-ros2-importer
```

**Comment by prasuchit** [comment]
Hi @lukicdarkoo ,

Thanks for getting back to me. I followed all the instructions correctly and these are the packages I have in the webots repo (develop branch):

simulator_ws/src/webots_ros2$ ls
CODE_OF_CONDUCT.md  webots_ros2_control   webots_ros2_tesla
CONTRIBUTING.md     webots_ros2_core      webots_ros2_tests
LICENSE             webots_ros2_driver    webots_ros2_tiago
README.md           webots_ros2_epuck     webots_ros2_turtlebot
docs                webots_ros2_importer  webots_ros2_universal_robot
scripts             webots_ros2_mavic
webots_ros2         webots_ros2_msgs

However, I did use the apt install command and it installed the webots-ros2-importer pkg successfully. I recompiled and sourced my ws just in case and when I tried again, this is what I saw:

[INFO] [launch]: All log files can be found below /home/ros/.ros/log/2022-09-02-13-16-01-931218-asus-zenbook-2010
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py:226> exception=SubstitutionFailure("executable 'ros2_supervisor.py' not found on the libexec directory '/home/ros/workspaces/simulator_ws/install/webots_ros2_driver/lib/webots_ros2_driver' ")>
Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  [Previous line repeated 1 more time]
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch_ros/actions/node.py", line 484, in execute
    ret = super().execute(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/actions/execute_process.py", line 837, in execute
    self.__expand_substitutions(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/actions/execute_process.py", line 681, in __expand_substitutions
    cmd = [perform_substitutions(context, x) for x in self.__cmd]
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/actions/execute_process.py", line 681, in <listcomp>
    cmd = [perform_substitutions(context, x) for x in self.__cmd]
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in perform_substitutions
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in <listcomp>
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_context.py", line 197, in perform_substitution
    return substitution.perform(self)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch_ros/substitutions/executable_in_package.py", line 84, in perform
    raise SubstitutionFailure(
launch.substitutions.substitution_failure.SubstitutionFailure: executable 'ros2_supervisor.py' not found on the libexec directory '/home/ros/workspaces/simulator_ws/install/webots_ros2_driver/lib/webots_ros2_driver'



Is it right that it is looking for the ros2_supervisor in the libexec dir of the webots_ros2_driver??
